baseURL = 'http://motss.cc/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh'
title = 'é…·å„¿è®ºå› | MOTSS'
theme = 'motsslib'

enableGitInfo = true
sectionPagesMenu = 'main'
paginate= 6

[permalinks]
  event = '/:sections/:year-:month-:day/'

[markup.goldmark.renderer]
unsafe= true

[[menu.static]]
  name = 'ğŸ’–æèµ '
  pageRef = '/support'
  weight = 10

[params]
  copyright = "[MOTSS Forum](https://motss.cc/)"
  description = "é…·å„¿è®ºå›ä¸ºæ­å·é«˜æ ¡æ€§å°‘æ•°äººç¾¤è¥é€ ä¸€ä¸ªå¤šå…ƒã€å¥åº·ã€å¹³ç­‰çš„ç¯å¢ƒï¼Œä¿ƒè¿›è‡ªæˆ‘è®¤åŒä¸ç¤¾ä¼šè®¤å¯ã€‚"
  title = "é…·å„¿è®ºå›"
  defaultAuthor = "è‹¦ç“œç“œ"
  resourceUrlPrefix = "https://motss.cc/archives/wechat/html/å›¾ç‰‡/é…·å„¿è®ºå›"
  footer = '<a href="{{< relref "/" >}}"><img src="/34d81d63fc27cfbe190bbcb3c6c5412c65b04086.png" height="20px"/><span>Â·</span><strong>å¤šå…ƒ Ã— å¥åº· Ã— å¹³ç­‰</strong></a>'

  dateFormat = "Jan 02, 2006"
  favicon = "favicon.png"
